[phases.setup]
nixPkgs = ["nodejs_18", "python3", "gcc", "g++"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --no-optional"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm preview"