export const countries = [
  { code: '+1', name: 'Estados Unidos', iso: 'US', flag: '🇺🇸' },
  { code: '+52', name: 'México', iso: 'MX', flag: '🇲🇽' },
  { code: '+34', name: 'España', iso: 'ES', flag: '🇪🇸' },
  { code: '+54', name: 'Argentina', iso: 'AR', flag: '🇦🇷' },
  { code: '+57', name: 'Colombia', iso: 'CO', flag: '🇨🇴' },
  { code: '+51', name: 'Perú', iso: 'PE', flag: '🇵🇪' },
  { code: '+56', name: 'Chile', iso: 'CL', flag: '🇨🇱' },
  { code: '+55', name: 'Brasil', iso: 'BR', flag: '🇧🇷' },
  { code: '+593', name: 'Ecuador', iso: 'EC', flag: '🇪🇨' },
  { code: '+58', name: 'Venezuela', iso: 'VE', flag: '🇻🇪' },
  { code: '+506', name: 'Costa Rica', iso: 'CR', flag: '🇨🇷' },
  { code: '+507', name: 'Panamá', iso: 'PA', flag: '🇵🇦' },
  { code: '+53', name: 'Cuba', iso: 'CU', flag: '🇨🇺' },
  { code: '+1', name: 'Canadá', iso: 'CA', flag: '🇨🇦' },
  { code: '+44', name: 'Reino Unido', iso: 'GB', flag: '🇬🇧' },
  { code: '+49', name: 'Alemania', iso: 'DE', flag: '🇩🇪' },
  { code: '+33', name: 'Francia', iso: 'FR', flag: '🇫🇷' },
  { code: '+39', name: 'Italia', iso: 'IT', flag: '🇮🇹' },
  { code: '+81', name: 'Japón', iso: 'JP', flag: '🇯🇵' },
  { code: '+86', name: 'China', iso: 'CN', flag: '🇨🇳' },
  { code: '+91', name: 'India', iso: 'IN', flag: '🇮🇳' },
  { code: '+7', name: 'Rusia', iso: 'RU', flag: '🇷🇺' },
  { code: '+61', name: 'Australia', iso: 'AU', flag: '🇦🇺' },
  { code: '+64', name: 'Nueva Zelanda', iso: 'NZ', flag: '🇳🇿' },
  // ...add more as needed
] 